name: Deploy Hugo Site

on:
  push:
    branches:
      - dev  # Set to your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: shirologic/cpvr-test-site:latest  # Change to your DockerHub username and repo

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull shirologic/cpvr-test-site:latest
            docker stop cpvr-test-site || true
            docker rm cpvr-test-site || true
            docker run -d --name cpvr-test-site -p 9800:80 shirologic/cpvr-test-site:latest
